collections:
  blog: '/blog/{year}/{month}/{day}/{slug}'
  things: '/facility/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
routes:
  /blog/tags: blog/taxonomies
  /search: search
  /users: user/index
  /users/{username}: user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
  /facility/feed:
    layout: feed
    template: feeds/things
    content_type: atom
  /sitemap:
    template: sitemap
    layout: sitemap
    content_type: xml
  /resources/sitemap-html:
    template: sitemap-html
    layout: sitemap-html
